# Site settings

author: 妙咩
email: eomie@outlook.com
github_username:  mierenai

head-title: MieShareCenter
title: MieShareCenter

baseurl: ""    # the subpath of your site, "/blog"
url: "https://mierenai.github.io"

# footer 
description: "妙咩的文件分享站."

favo: "文能提笔控萝莉，武能床上定人妻"
descrpt: "虽说也能做到将其无视，但还需要一些努力。"


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

